### ISSUE TITLE
signature algorithm deprecated

### ISSUE THREAD

**Issue by ghost** [froala/wysiwyg-editor-ruby-sdk#3]
uploading image to S3 directly with official Froala ruby SDK occurs error `The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.` from AWS.

https://docs.aws.amazon.com/general/latest/gr/signature-v4-examples.html

**Comment by devhbh** [comment]
comment: it occurs only in region which was created after 2014/01/30.

**Comment by JoelESvensson** [comment]
I just got hit with this when evaluating Froala using the Frankfurt region.

**Comment by ndeto** [comment]
I created a separate bucket us-east-1 (US N. Virginia) which used to be US Standard. It worked

**Comment by acahinton** [comment]
same issue on eu-west-2 - forced to locate bucket in eu-west-1 to resolve...

**Comment by joneidejohnsen** [comment]
Any response from the devs here?

**Comment by joneidejohnsen** [comment]
I'm still receiving the same error as before: `The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.`

Is the official gem also updated? According to [https://rubygems.org/gems/froala-editor-sdk/versions/1.2.0](https://rubygems.org/gems/froala-editor-sdk/versions/1.2.0) the gem was last updated August 14 2017 – or am I missing something here?

**Comment by stefanneculai** [comment]
It's not published yet on the gem - it's only on master branch at this moment. We will publish it in a few weeks.

**Comment by joneidejohnsen** [comment]
Thanks for the quick reply! Out of curiosity, why can't this be done at once?

**Comment by stefanneculai** [comment]
We're on the QA phase for the merged changes and need some final tests to be run.

**Comment by joneidejohnsen** [comment]
What's the progress here, @stefanneculai ?

**Comment by stefanneculai** [comment]
It's been approved by QA and we're going to tag this as a new release next week.
