### ISSUE TITLE
Requires prehistoric version of wysiwyg-rails (2.6.6)

### ISSUE THREAD

**Issue by fjaeger** [froala/wysiwyg-editor-ruby-sdk#4]
Somehow installing this ruby SDK requires a very old version of your great wysiwyg-rails – 2.6.6.

Is this a hard requirement or did somebody forgot to update the Gemfile or the corresponding lock file?

Would be great to use the latest and greatest version of wysiwyg-rails together with the ruby SDK!

**Comment by brendon** [comment]
It should read:

```
gem.add_dependency 'wysiwyg-rails', '~> 2.6'
```

To allow for any release in the 2.x series.

**Comment by kreintjes** [comment]
Same problem over here. We are still using Froala Editor 2.6.6, while 2.8.4 is long since available.

**Comment by Holist** [comment]
Same here...

**Comment by kreintjes** [comment]
@Holist and others: there's a PR with a fix here: https://github.com/froala/wysiwyg-editor-ruby-sdk/pull/8. You can use my fork until it gets merged: `gem 'froala-editor-sdk', '~> 1.2', git: 'https://github.com/kreintjes/wysiwyg-editor-ruby-sdk', branch: 'fix/loosen-locks'`

**Comment by brendon** [comment]
Maybe ping @stefanneculai via email through their support system to get this hurried along? Are you paying customers?

I ended up not using this gem as it's actually quite easy to write your own interface, and more flexible too. There are a few other bugs too that need fixing (See my open issues).

**Comment by Holist** [comment]
Im a paying customer and opened a ticket on support for this today. thanks @kreintjes for this.

**Comment by brendon** [comment]
Thanks @stefanneculai :)
